apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: admin
build:
  artifacts:
    - image: postgres
      context: k8s/db/psql/development/
    - image: migration-admin
      context: k8s/db/psql/development/migration_admin
    - image: notifications
      context: services/notifications/
    - image: admin
      context: services/admin/
profiles:
  - name: admin-db-check
    test:
      - image: admin
        structureTests:
          - './services/structure-test/admin_db.yaml'
deploy:
  # Default is minikube
  #  kubeContext: kind-kind
  # kubeContext: k3d-local
  kubectl:
    manifests:
      - k8s/namespaces/services-ns.yaml
      - k8s/configmaps/development/configmap.yaml
      - k8s/secrets/development/secret.yaml
      - k8s/security_profiles/seccomp/profiles/secured-profile-development.yaml
      - k8s/storage/psql/pv-data-complete.yaml
      - k8s/storage/psql/pvc-data-complete.yaml
      - k8s/db/psql/development/deployment.yaml
      - k8s/db/psql/development/service.yaml
      - k8s/db/psql/development/migration_admin/run-migration.yaml
      - k8s/services/admin/deployment.yaml
      - k8s/services/admin/service.yaml
      - k8s/services/notifications/deployment.yaml
      - k8s/services/notifications/service.yaml
      - k8s/ingress/develop/ingress.yml
