apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-data-complete
  namespace: services
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/greenbone"
