apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-data-complete
  namespace: services
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
