apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: services
  labels:
    app: admin
spec:
  selector:
    app: admin
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 32020
