apiVersion: batch/v1
kind: Job
metadata:
  name: migration-admin
  namespace: services
spec:
  template:
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: admin-secret
      initContainers:
        - image: postgres
          name: postgres
          command: ['sh', '-c', 'sleep 10; pg_isready -h $POSTGRES_SERVICE_HOST -p $POSTGRES_SERVICE_PORT -d admin; sleep 10;']
          securityContext:
            runAsNonRoot: true
            runAsUser: 70
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: Localhost
              localhostProfile: operator/services/secured-profile.json
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: admin-config
            - secretRef:
                name: admin-secret
      containers:
        - name: migration-admin
          image: migration-admin
          imagePullPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 70
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: Localhost
              localhostProfile: operator/services/secured-profile.json
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret"
          command: ["./run_migration.sh"]
          envFrom:
            - configMapRef:
                name: admin-config
            - secretRef:
                name: admin-secret
      restartPolicy: Never
  backoffLimit: 4