apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: services
  labels:
    app: notifications
spec:
  selector:
    app: notifications
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 32021
